services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - .env
    ports:
      - 8080:8080 # qBittorrent WebUI
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/Configs_Backups/Services/qbittorrent:/config
      - /mnt/media_datatank2/downloads:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - API_KEY=446e6c1985fc47519a27a71c0c25fbf2
    volumes:
      - /mnt/Configs_Backups/Services/sonarr:/config
      - /mnt/media_datatank2/downloads:/downloads
      - /mnt/media_datatank2/shows:/tv
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - API_KEY=61f61cd0ae104764adbff4553fb48588
    volumes:
      - /mnt/Configs_Backups/Services/radarr:/config
      - /mnt/media_datatank2/downloads:/downloads
      - /mnt/media_datatank2/movies:/movies
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - API_KEY=0093aceb5f0f4882abde3fc75f8d7057
    volumes:
      - /mnt/Configs_Backups/Services/prowlarr:/config
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/Configs_Backups/Services/jellyfin:/config
      - /mnt/media_datatank2/shows:/data/tvshows
      - /mnt/media_datatank2/movies:/data/movies
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - 5055:5055
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/Configs_Backups/Services/jellyseerr:/app/config
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - 8191:8191
    environment:
      - TZ=America/New_York
      - LOG_LEVEL=info
      - BROWSER_TIMEOUT=120000
    restart: unless-stopped
